### ISSUE TITLE
Hostnames for Exit Nodes

### ISSUE THREAD

**Issue by ticky** [saumya-banthia/tailscale-control#14]
Hi there, Just wondering if you'd be open to a patch to show the hostnames in addition to, or instead of, the exit node IPs, in the menu. This would more closely match the behaviour of Tailscale's first-party GUI tools. Thanks!

**Comment by saumya-banthia** [comment]
> Hi there, Just wondering if you'd be open to a patch to show the hostnames in addition to, or instead of, the exit node IPs, in the menu. This would more closely match the behaviour of Tailscale's first-party GUI tools. Thanks!

Open to that patch - please ensure in the changes that you raise as a PR, it is in addition to the IP, not instead of (with the host name being inside brackets). Also, I would recommend waiting till [PR#12](https://github.com/saumya-banthia/tailscale-control/pull/12) is complete to create a patch.

If I happen to find some time to look into it as part of the above mentioned PR, I will add it to the same PR.

**Comment by saumya-banthia** [comment]
Closing

**Comment by ticky** [comment]
Just got the update in my Decky! Wow, thanks for turning it around so quick haha.
